import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { generateOGImage } from '../lib/generate-og-image'

const Home = () => {
  return (
    <div>
      <Head>
        <title>OG Image</title>
        <meta name="description" content="Generated by OG Image" />
      </Head>

      <main>
        <h1>Welcome to OG Image</h1>
        <p style={{ fontSize: 20 }}>
          <b>og-image.jpeg</b> is generated at <b>public/</b> folder. To change
          the og image, edit <b>pages/og-image-preview.tsx</b>!
        </p>
        <Link href="/og-image-preview">Preview OG Image</Link>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  generateOGImage()
  return { props: {} }
}

export default Home
