import { GetStaticProps } from 'next'
import Head from 'next/head'

import { generateOGImage } from '../lib/generate-og-image'

function Home() {
  return (
    <div>
      <Head>
        <title>OG Image</title>
        <meta name="description" content="Generated by OG Image" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to OG Image</h1>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  generateOGImage()
  return { props: {} }
}

export default Home
